# Generated by Django 5.2.9 on 2025-12-03 16:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('email', models.EmailField(help_text='The email address must be unique for each feedback submission.', max_length=254, unique=True)),
                ('rating', models.IntegerField(help_text='The rating score must be between 1 and 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
    ]
